### ISSUE TITLE
PPI TRAINING :TypeError: index_select(): argument 'index' (position 3) must be Tensor, not NoneType 

### ISSUE THREAD

**Issue by Charlie4zc** [GraphNAS/GraphNAS#5]
`2019-06-24 03:22:10,338:INFO::NAS-like mode: retrain without share param
Namespace(batch_size=64, controller_grad_clip=0, controller_lr=0.00035, controller_max_step=5, controller_optim='adam', cuda=True, dataset='PPI', derive_num_sample=100, discount=1.0, ema_baseline_decay=0.95, entropy_coeff=0.0001, entropy_mode='reward', epochs=50, in_drop=0, in_feats=50, layers_of_child_model=3, load_path='', lr=0.005, max_epoch=200, max_param=5000000.0, max_save_num=5, mode='train', multi_label=False, num_class=121, optim_file='opt_cora_test.pkl', param_file='cora_test.pkl', random_seed=123, residual=True, retrain_epochs=200, save_epoch=5, search_mode='nas', share_param=False, shared_initial_step=0, shared_rnn_max_length=35, softmax_temperature=5.0, tanh_c=2.5, weight_decay=0)
*********************************** training controller ***********************************
/home/XX/.local/lib/python3.6/site-packages/torch/nn/functional.py:1374: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
train action: ['gat', 'sum', 'relu', 2, 8, 'linear', 'mlp', 'tanh', 2, 4, 'gat_sym', 'sum', 'linear', 6, 121]
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main(args)
  File "main.py", line 100, in main
    trnr.train()
  File "/home/XX/ws2/GraphNAS-simple/trainer.py", line 105, in train
    self.train_controller()
  File "/home/XX/ws2/GraphNAS-simple/trainer.py", line 191, in train_controller
    results = self.get_reward(structure_list, np_entropies, hidden)
  File "/home/XX/ws2/GraphNAS-simple/trainer.py", line 151, in get_reward
    reward = self.shared.test_with_param(actions, with_retrain=self.with_retrain)
  File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_gnn_ppi_manager.py", line 145, in test_with_param
    return self.train(actions, format)
  File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_gnn_ppi_manager.py", line 95, in train
    total_loss = self.run_model(model, optimizer, loss_op)
  File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_gnn_ppi_manager.py", line 119, in run_model
    loss = loss_op(model(data.x, data.edge_index), data.y)
  File "/home/XX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_gnn.py", line 70, in forward
    output = act(layer(output, edge_index_all) + fc(output))
  File "/home/XX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_layer.py", line 109, in forward
    return self.propagate(edge_index, x=x, num_nodes=x.size(0))
  File "/home/XX/ws2/GraphNAS-simple/models/geo/message_passing.py", line 81, in propagate
    tmp = torch.index_select(tmp, 0, edge_index[idx])
TypeError: index_select(): argument 'index' (position 3) must be Tensor, not NoneType`

**Comment by ColdenChan** [comment]
> `2019-06-24 03:22:10,338:INFO::NAS-like mode: retrain without share param Namespace(batch_size=64, controller_grad_clip=0, controller_lr=0.00035, controller_max_step=5, controller_optim='adam', cuda=True, dataset='PPI', derive_num_sample=100, discount=1.0, ema_baseline_decay=0.95, entropy_coeff=0.0001, entropy_mode='reward', epochs=50, in_drop=0, in_feats=50, layers_of_child_model=3, load_path='', lr=0.005, max_epoch=200, max_param=5000000.0, max_save_num=5, mode='train', multi_label=False, num_class=121, optim_file='opt_cora_test.pkl', param_file='cora_test.pkl', random_seed=123, residual=True, retrain_epochs=200, save_epoch=5, search_mode='nas', share_param=False, shared_initial_step=0, shared_rnn_max_length=35, softmax_temperature=5.0, tanh_c=2.5, weight_decay=0) *********************************** training controller *********************************** /home/XX/.local/lib/python3.6/site-packages/torch/nn/functional.py:1374: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead. warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.") train action: ['gat', 'sum', 'relu', 2, 8, 'linear', 'mlp', 'tanh', 2, 4, 'gat_sym', 'sum', 'linear', 6, 121] Traceback (most recent call last): File "main.py", line 111, in <module> main(args) File "main.py", line 100, in main trnr.train() File "/home/XX/ws2/GraphNAS-simple/trainer.py", line 105, in train self.train_controller() File "/home/XX/ws2/GraphNAS-simple/trainer.py", line 191, in train_controller results = self.get_reward(structure_list, np_entropies, hidden) File "/home/XX/ws2/GraphNAS-simple/trainer.py", line 151, in get_reward reward = self.shared.test_with_param(actions, with_retrain=self.with_retrain) File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_gnn_ppi_manager.py", line 145, in test_with_param return self.train(actions, format) File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_gnn_ppi_manager.py", line 95, in train total_loss = self.run_model(model, optimizer, loss_op) File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_gnn_ppi_manager.py", line 119, in run_model loss = loss_op(model(data.x, data.edge_index), data.y) File "/home/XX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__ result = self.forward(*input, **kwargs) File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_gnn.py", line 70, in forward output = act(layer(output, edge_index_all) + fc(output)) File "/home/XX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__ result = self.forward(*input, **kwargs) File "/home/XX/ws2/GraphNAS-simple/models/geo/geo_layer.py", line 109, in forward return self.propagate(edge_index, x=x, num_nodes=x.size(0)) File "/home/XX/ws2/GraphNAS-simple/models/geo/message_passing.py", line 81, in propagate tmp = torch.index_select(tmp, 0, edge_index[idx]) TypeError: index_select(): argument 'index' (position 3) must be Tensor, not NoneType`

I have the same issue.

**Comment by yvquanli** [comment]
+1, except for some idea from author

**Comment by yvquanli** [comment]
+1， look forward to getting some ideas from the author

**Comment by GaoYangIIE** [comment]
You can try to replace the original model/geo/geo_layer.py with this code. This problem is mainly caused by the inconsistent version of PYG.

`
import torch
import torch.nn.functional as F
from torch.nn import Parameter
from torch_geometric.nn.inits import glorot, zeros
from torch_geometric.utils import remove_self_loops, add_self_loops, add_remaining_self_loops, softmax
from torch_scatter import scatter_add

from models.geo import MessagePassing


class GeoLayer(MessagePassing):

    def __init__(self,
                 in_channels,
                 out_channels,
                 heads=1,
                 concat=True,
                 negative_slope=0.2,
                 dropout=0,
                 bias=True,
                 att_type="gat",
                 agg_type="sum",
                 pool_dim=0):
        if agg_type in ["sum", "mlp"]:
            super(GeoLayer, self).__init__('add')
        elif agg_type in ["mean", "max"]:
            super(GeoLayer, self).__init__(agg_type)
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.heads = heads
        self.concat = concat
        self.negative_slope = negative_slope
        self.dropout = dropout
        self.att_type = att_type
        self.agg_type = agg_type

        # GCN weight
        self.gcn_weight = None

        self.weight = Parameter(
            torch.Tensor(in_channels, heads * out_channels))
        self.att = Parameter(torch.Tensor(1, heads, 2 * out_channels))

        if bias and concat:
            self.bias = Parameter(torch.Tensor(heads * out_channels))
        elif bias and not concat:
            self.bias = Parameter(torch.Tensor(out_channels))
        else:
            self.register_parameter('bias', None)

        if self.att_type in ["generalized_linear"]:
            self.general_att_layer = torch.nn.Linear(out_channels, 1, bias=False)

        if self.agg_type in ["mean", "max", "mlp"]:
            if pool_dim <= 0:
                pool_dim = 128
        self.pool_dim = pool_dim
        if pool_dim != 0:
            self.pool_layer = torch.nn.ModuleList()
            self.pool_layer.append(torch.nn.Linear(self.out_channels, self.pool_dim))
            self.pool_layer.append(torch.nn.Linear(self.pool_dim, self.out_channels))
        else:
            pass
        self.reset_parameters()

    @staticmethod
    def norm(edge_index, num_nodes, edge_weight, improved=False, dtype=None):
        if edge_weight is None:
            edge_weight = torch.ones((edge_index.size(1), ),
                                     dtype=dtype,
                                     device=edge_index.device)

        fill_value = 1 if not improved else 2
        edge_index, edge_weight = add_remaining_self_loops(
            edge_index, edge_weight, fill_value, num_nodes)

        row, col = edge_index
        deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
        deg_inv_sqrt = deg.pow(-0.5)
        deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0

        return edge_index, deg_inv_sqrt[row] * edge_weight * deg_inv_sqrt[col]

    def reset_parameters(self):
        glorot(self.weight)
        glorot(self.att)
        zeros(self.bias)

        if self.att_type in ["generalized_linear"]:
            glorot(self.general_att_layer.weight)

        if self.pool_dim != 0:
            for layer in self.pool_layer:
                glorot(layer.weight)
                zeros(layer.bias)

    def forward(self, x, edge_index):
        """"""
        edge_index, _ = remove_self_loops(edge_index)
        edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        # prepare
        x = torch.mm(x, self.weight).view(-1, self.heads, self.out_channels)
        return self.propagate(edge_index, x=x, num_nodes=x.size(0))

    def message(self, x_i, x_j, edge_index, num_nodes):

        if self.att_type == "const":
            if self.training and self.dropout > 0:
                x_j = F.dropout(x_j, p=self.dropout, training=True)
            neighbor = x_j
        elif self.att_type == "gcn":
            if self.gcn_weight is None or self.gcn_weight.size(0) != x_j.size(0):  # 对于不同的图gcn_weight需要重新计算
                _, norm = self.norm(edge_index, num_nodes, None)
                self.gcn_weight = norm
            neighbor = self.gcn_weight.view(-1, 1, 1) * x_j
        else:
            # Compute attention coefficients.
            alpha = self.apply_attention(edge_index, num_nodes, x_i, x_j)
            alpha = softmax(alpha, edge_index[0], num_nodes)
            # Sample attention coefficients stochastically.
            if self.training and self.dropout > 0:
                alpha = F.dropout(alpha, p=self.dropout, training=True)

            neighbor = x_j * alpha.view(-1, self.heads, 1)
        if self.pool_dim > 0:
            for layer in self.pool_layer:
                neighbor = layer(neighbor)
        return neighbor

    def apply_attention(self, edge_index, num_nodes, x_i, x_j):
        if self.att_type == "gat":
            alpha = (torch.cat([x_i, x_j], dim=-1) * self.att).sum(dim=-1)
            alpha = F.leaky_relu(alpha, self.negative_slope)

        elif self.att_type == "gat_sym":
            wl = self.att[:, :, :self.out_channels]  # weight left
            wr = self.att[:, :, self.out_channels:]  # weight right
            alpha = (x_i * wl).sum(dim=-1) + (x_j * wr).sum(dim=-1)
            alpha_2 = (x_j * wl).sum(dim=-1) + (x_i * wr).sum(dim=-1)
            alpha = F.leaky_relu(alpha, self.negative_slope) + F.leaky_relu(alpha_2, self.negative_slope)

        elif self.att_type == "linear":
            wl = self.att[:, :, :self.out_channels]  # weight left
            wr = self.att[:, :, self.out_channels:]  # weight right
            al = x_j * wl
            ar = x_j * wr
            alpha = al.sum(dim=-1) + ar.sum(dim=-1)
            alpha = torch.tanh(alpha)
        elif self.att_type == "cos":
            wl = self.att[:, :, :self.out_channels]  # weight left
            wr = self.att[:, :, self.out_channels:]  # weight right
            alpha = x_i * wl * x_j * wr
            alpha = alpha.sum(dim=-1)

        elif self.att_type == "generalized_linear":
            wl = self.att[:, :, :self.out_channels]  # weight left
            wr = self.att[:, :, self.out_channels:]  # weight right
            al = x_i * wl
            ar = x_j * wr
            alpha = al + ar
            alpha = torch.tanh(alpha)
            alpha = self.general_att_layer(alpha)
        else:
            raise Exception("Wrong attention type:", self.att_type)
        return alpha

    def update(self, aggr_out):
        if self.concat is True:
            aggr_out = aggr_out.view(-1, self.heads * self.out_channels)
        else:
            aggr_out = aggr_out.mean(dim=1)

        if self.bias is not None:
            aggr_out = aggr_out + self.bias
        return aggr_out

    def __repr__(self):
        return '{}({}, {}, heads={})'.format(self.__class__.__name__,
                                             self.in_channels,
                                             self.out_channels, self.heads)

    def get_param_dict(self):
        params = {}
        key = f"{self.att_type}_{self.agg_type}_{self.in_channels}_{self.out_channels}_{self.heads}"
        weight_key = key + "_weight"
        att_key = key + "_att"
        agg_key = key + "_agg"
        bais_key = key + "_bais"

        params[weight_key] = self.weight
        params[att_key] = self.att
        params[bais_key] = self.bias
        if hasattr(self, "pool_layer"):
            params[agg_key] = self.pool_layer.state_dict()

        return params

    def load_param(self, params):
        key = f"{self.att_type}_{self.agg_type}_{self.in_channels}_{self.out_channels}_{self.heads}"
        weight_key = key + "_weight"
        att_key = key + "_att"
        agg_key = key + "_agg"
        bais_key = key + "_bais"

        if weight_key in params:
            self.weight = params[weight_key]

        if att_key in params:
            self.att = params[att_key]

        if bais_key in params:
            self.bias = params[bais_key]

        if agg_key in params and hasattr(self, "pool_layer"):
            self.pool_layer.load_state_dict(params[agg_key])

`

**Comment by yvquanli** [comment]
it works, exciting news for me, thanks 😃😆
