### ISSUE TITLE
no requests module in the docker file--Better to update the DockerFile

### ISSUE THREAD

**Issue by PhoenixZhao** [GraphNAS/GraphNAS#7]
@GraphNAS Nice work and thanks for releasing this code. 

I was trying to reproduce your work recently, and it is helpful you released a docker version.
Currently, the requests model is missing from the DockerFile, and it will be great for people if you can add the package "requests" in the DockerFile.

**Comment by GraphNAS** [comment]
Thanks for mention it. I've updated the DockerFile.
